# Override file for development - disables nginx and enables development features
services:
  backend:
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${BACKEND_PORT:-3003}:3003"
      - "9229:9229" # Debug port
    working_dir: /usr/src/app
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.js"]

  frontend:
    # Rebuild for development with source code
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    # Override the production CMD to use dev server
    working_dir: /app/apps/frontend
    command: ["pnpm", "dev", "--hostname", "0.0.0.0"]

  # Disable nginx for development
  nginx:
    profiles:
      - production
