services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3003/api
    working_dir: /app
    command: >
      sh -c "pnpm install --frozen-lockfile && pnpm --filter frontend dev"
    volumes:
      - ./apps:/app/apps
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./tsconfig.json:/app/tsconfig.json
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb+srv://yuganPaka:7P9VQ20Fvj3pfztn@myblog.yioj9or.mongodb.net/?retryWrites=true&w=majority&appName=myBlog
      - NODE_ENV=development
      - DB_CONNECT_RETRIES=5
      - DB_CONNECT_TIMEOUT=10000
    command: pnpm start
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
      


networks:
  default:
    name: myBlog-network
