
const mongoose = require('mongoose');

const CommentSchema = new mongoose.Schema({
  postId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BlogPost', // Reference to the BlogPost model
    required: true,
    index: true // Subtask 1.3: Add an index on postId
  },
  authorName: {
    type: String,
    required: true
  },
  commentText: {
    type: String,
    required: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

// Subtask 1.2: _id is automatically generated by Mongoose

module.exports = mongoose.model('Comment', CommentSchema);
